import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/main.css";
import Providor from "./Providor";
import Navbar from "@/components/Navbar";
import { FONT_VARIABLES } from "@/config/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${FONT_VARIABLES} antialiased`}>
        <Providor>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <div className="pt-12">{children}</div>
          </div>
        </Providor>
      </body>
    </html>
  );
}
